const data = {
  products: [
    {
      name: 'Milo',
      slug: 'milo',
      category: 'Beverage',
      image: '/image/milo.jpg',
      price: 5,
      countInStock: 10,
      brand: 'Nestle',
      rating: 4.5,
      numReviews: 2,
      description: 'great chocolate and milk drink',
    },
    {
      name: 'Malt',
      slug: 'malt',
      category: 'Beverage',
      image: '/image/malt.jpg',
      price: 6,
      countInStock: 20,
      brand: 'Guiness',
      rating: 4.5,
      numReviews: 2,
      description: 'malt drink',
    },
    {
      name: 'Indomie',
      slug: 'indomie',
      category: 'Noodles',
      image: '/image/indomie.jpg',
      price: 12.99,
      countInStock: 34,
      brand: 'Indomie',
      rating: 4.5,
      numReviews: 2,
      description: 'instant noodles',
    },
    {
      name: 'Tom Brown',
      slug: 'tom-brown',
      category: 'porridge',
      image: '/image/tom-brown.jpg',
      price: 3.99,
      countInStock: 5,
      brand: 'Harveys',
      rating: 4.5,
      numReviews: 2,
      description: 'quick porridge',
    },
    {
      name: 'Plantain Chips',
      slug: 'plantain-chips',
      category: 'Chips',
      image: '/image/plan-chip.jpg',
      price: 1.6,
      countInStock: 8,
      brand: 'Nondo',
      rating: 4.5,
      numReviews: 2,
      description: 'fried ripe plantain chips',
    },
  ],
};

export default data;
